ADCIO-2463) feat: update module architecture
corca-ai/adcio_core pull request #7
Opened 2024-02-15 06:24 UTC by aahspringaa4

♻️ Current situation
* 현재 adcio core가 플러그인 로직상 꼭 필요한지 의문
* adcio core가 없을 경우 id 값들을 한번에 어디서 관리 할지 애매했음
* 기존 adcio core의 역할은 지우고 단순 core 모듈로써의 책임 변경
 
💡 Proposed solution
* adcio core 책임 변경 (사이드 이팩트가 없는 코드만 포함하여 제공함)
* ADCIO 전용 Core 모듈 -> 어디서나 사용 가능한 Core 모듈 
  * deviceId sessionId 제공

2024-02-15 07:48 UTC, adbr-dev commented
**♻️ Current situation**

- 현재 adcio core가 플러그인 로직상 꼭 필요한지 의문
- 기존 adcio core의 역할은 지우고 단순 core 모듈로써의 책임 변경

**💡 Proposed solution**

- 사이드 이팩트가 없는 코드만 제공
  - deviceId, sessionId 제공
  - clientID 제거 
- 관련 자세한 내용 해당 [노션](https://www.notion.so/corcaai/0131_-by-iOS-8d7c8c1ba07245e99e923bfe6d86fcf1) 참고

이렇게 맞죵?? @aahspringaa4

2024-02-15 07:51 UTC, adbr-dev commented on lib/adcio_core.dart
fetch_device_id도 같이 session_client처럼 같은 역할인데 파일명이랑 구조가 통일화 되어야 될 것 같아요
session_client가 네이밍이 맞는지 조금 갸우뚱한데 네이밍 조금만 더 고민해보시죠 .. ㅎ

2024-02-16 01:36 UTC, adbr-dev requested changes

2024-02-16 01:36 UTC, adbr-dev commented on lib/src/device_identifier.dart
오 identifier 좋은데요? ㅋㅋㅋㅋid를 결국 풀어쓰는 형태로 되었군여

lib/src/session_identifier.dart
있는대로 _identifier,  _createIdentifier()와 동일한 구조로 통일성 맞춰주세요 !

2024-02-19 02:30 UTC, aahspringaa4 commented on lib/src/device_identifier.dart
> _identifier, _createIdentifier()와 동일한 구조로 통일성 맞춰주세요 !

ㅠㅠ 저 이 말을 이해 못했어요..  **loadId -> loadIdentifier** 일까요??

2024-02-21 02:22 UTC, adbr-dev approved these changes
귯 !

2024-02-21 02:24 UTC, merged